word1 = input('Eneter word1: ')
word2 = input('Enter word2: ')
word3 = input('Enter word3: ')
word4 = input(' Enter word 4: ')
print("{} are red".format(word1))
print(f"Violets are {word2}")
print("I love "+ word3)
print(f"This is amazing{word4}")
print("I have to go "+word2)
print("Nope you shouldnt be going :/"+word1)